# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7107814087659f6ab4b4a90682b43cec01016a5b2493f7889a02a6c12b7bbdce868c1a743cbce68da38c914be348700eec709927c59b6f99b44d57d947d736b5

test:
  secret_key_base: 612dee098887e866790f3ed256992bc854c6d478a0c17ec4135c7df48740e015136f9fa5e08862dcf824576501c964415aa3295f98adf8a96fa932792158c077

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
